version: '3'

services:

  spring-todo-app:
    build: .
    restart: on-failure
    container_name: spring_todo_app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    depends_on:
      - postgres-todo
    networks:
      - todo_net

  postgres-todo:
    image: postgres:14
    container_name: postgres_todo
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - .volumes/postgres:/var/lib/postgres
    networks:
      - todo_net

networks:
  todo_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"
